<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="D:\projects.git\My-Exercism-Solutions\delphi\perfect-numbers\PerfectNumbers.exe" total="13" errors="0" failures="0" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2019-03-26" time="6.146">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="PerfectNumbers.exe" executed="true" result="Success" success="True" time="6.146" asserts="0">
    <results>
        <test-suite type="Namespace" name="uPerfectNumbersTest" executed="true" result="Success" success="True" time="6.146" asserts="0" >
          <results>
              <test-suite type="Fixture" name="PerfectNumbersTest" executed="True" result="Success" success="True" time="6.146" >
                <results>
                  <test-case name="Smallest_perfect_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Medium_perfect_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Large_perfect_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.088" asserts="0" />
                  <test-case name="Smallest_abundant_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Medium_abundant_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Large_abundant_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.082" asserts="0" />
                  <test-case name="Smallest_prime_deficient_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Smallest_non_prime_deficient_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Medium_deficient_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Large_deficient_number_is_classified_correctly" executed="True" result="Success" success="True" time="0.082" asserts="0" />
                  <test-case name="Edge_case_no_factors_other_than_itself_is_classified_correctly" executed="True" result="Success" success="True" time="0.000" asserts="0" />
                  <test-case name="Zero_is_rejected_not_a_natural_number" executed="True" result="Success" success="True" time="4.339" asserts="0" />
                  <test-case name="Negative_integer_is_rejected_not_a_natural_number" executed="True" result="Success" success="True" time="1.551" asserts="0" />
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
